### ISSUE TITLE
How to handle false positives

### ISSUE THREAD

**Issue by jhhuang7** [jhhuang7/Exploring-Suricata#4]

**Comment by EbrahimAlharbi** [comment]
https://suricata.readthedocs.io/en/suricata-4.1.3/make-sense-alerts.html

**Comment by EbrahimAlharbi** [comment]
Suricata’srule set detection accuracy is measured by malicious traffic in a controlled experiment environment
and compared the number of false positive, false negative and true positive alarms triggered by it.

False Positive Rate (FPR)
This is the likelihood that the IDS will trigger an alarm when there is no intrusion. This was measured by
FPR percentage. It triggers an excessive rate of false positive alarms when they do not accurately differentiate
between legitimate and malicious network traffic

True Positive (TP): True is identified as true, which is correct identification
True Negative (TN): False is identified as false, which is correct identification
False Positive (FP): True is identified as false, which is wrong identification
False Negative (FN): False is identified as true, which is wrong identification
P = TP + FN (number of correct identification)
N = FP + TN (number of wrong identification)
True Positive Rate (TPR) = TP / P = TP / (TP + FN) 
False Positive Rate (FPR) = FP / N = FP / (FP + TN) 
False Negative Rate (FNR) = FN / P = FN / (FN + TP) 

https://arxiv.org/ftp/arxiv/papers/1710/1710.04843.pdf

**Comment by EbrahimAlharbi** [comment]
False Alarm Rate = False Alarm/Total Alarm×100
file:///C:/Users/ebrah/Downloads/Tjhai2008_Chapter_InvestigatingTheProblemOfIDSFa.pdf
